name:                ray-marcher
version:             0.1.0.0
github:              "umnikos/haskell-ray-marcher"
license:             GPL-3
author:              "Alex&Alex"
maintainer:          "example@example.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/umnikos/haskell-ray-marcher#readme>

dependencies:
- base >= 4.7 && < 5
- ppm >= 2009.5.13

library:
  source-dirs: src
  exposed-modules:
  - Marcher
  - Marcher.Scenes

executables:
  hmarch:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-marcher

tests:
  hmarch-test:
    spec:
    defaults: hspec/hspec@master
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-marcher
